/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aaaa_test */

#ifndef _Included_com_example_aaaa_test
#define _Included_com_example_aaaa_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aaaa_test
 * Method:    myHelloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_aaaa_test_myHelloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
