/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noahedu_person_health_engine_Engine */

#ifndef _Included_com_noahedu_person_health_engine_Engine
#define _Included_com_noahedu_person_health_engine_Engine
#ifdef __cplusplus
extern "C" {
#endif


#undef com_noahedu_person_health_engine_Engine_ENGINE_VERSION
#define com_noahedu_person_health_engine_Engine_ENGINE_VERSION 2L
#undef com_noahedu_person_health_engine_Engine_INVALID_BOOK_HANDLER
#define com_noahedu_person_health_engine_Engine_INVALID_BOOK_HANDLER -1L
/*
 * Class:     com_noahedu_person_health_engine_Engine
 * Method:    nativeOpenPackages
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_noahedu_person_health_engine_Engine_nativeOpenPackages
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_noahedu_person_health_engine_Engine
 * Method:    nativeClosePackages
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_noahedu_person_health_engine_Engine_nativeClosePackages
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_noahedu_person_health_engine_Engine
 * Method:    nativeReadContent
 * Signature: (ILjava/lang/String;)[Lcom/noahedu/person/health/engine/Content;
 */
JNIEXPORT jobjectArray JNICALL Java_com_noahedu_person_health_engine_Engine_nativeReadContent
  (JNIEnv *, jclass, jint, jstring);
/*
 * Class:     com_noahedu_person_health_engine_Engine
 * Method:    nativeGetPictureInfo
 * Signature: (ILjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_noahedu_person_health_engine_Engine_nativeGetPictureInfo
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_noahedu_person_health_engine_Engine
 * Method:    nativeGetSignature
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_noahedu_person_health_engine_Engine_nativeGetSignature
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
